### ISSUE TITLE
Incorporate ideas from cedaro/structure

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-foo-bar#12]
See: 
http://www.cedaro.com/blog/structuring-wordpress-plugins/
https://github.com/cedaro/structure

**Comment by XedinUnknown** [comment]
I have a lot of experience with OOP, abstraction, and framework-agnostic architecture. I would be up for re-vamping the boilerplate to be more powerful and flexible. Please let me know if I can help, @westonruter, and we can talk about exactly how I could do that :)

**Comment by westonruter** [comment]
Sounds good. Happy to get your ideas. Also, I'd be interested in revamping this plugin into a WP-CLI scaffolding, perhaps extending https://github.com/wp-cli/scaffold-command

**Comment by rheinardkorf** [comment]
@westonruter it would be nice if we could extend WP-CLI in such a way that you can provide a GitHub project as a "template" to be used in the scaffolding.  E.g. scaffold without a template will give you the current scaffolded plugin; but providing something like `--repo=xwp/wp-foo-bar:master` would use this repo for scaffolding.

**Comment by XedinUnknown** [comment]
For easy "scaffolding", consider something like [dhii/bootstrap](https://github.com/Dhii/bootstrap/pull/1#issuecomment-286854604).
