### ISSUE TITLE
Update Plugin_Base with change made in Customize Snapshots

### ISSUE THREAD

**Issue by valendesigns** [xwp/wp-foo-bar#14]
The changes are from https://github.com/xwp/wp-customize-snapshots/pull/35/commits/164815c488b1fe10298a2c401e9e41ed68d5c625

This includes a fix/enhancement for `Plugin_Base::remove_doc_hooks`.

**Comment by lukecarbis** [comment]
Done in e468ab444a6a7d364928ed35daad8f3867ecf6bd.
