### ISSUE TITLE
add_doc_hooks fails if hook contains a slash

### ISSUE THREAD

**Issue by lukecarbis** [xwp/wp-foo-bar#21]
Some plugins use slashes in their hooks, and the add_doc_hooks method isn't correctly adding the actions or filters.

Example of an action with a slash: https://github.com/elliotcondon/acf/blob/master/core/api.php#L1116

**Comment by westonruter** [comment]
The issue is the regex here: https://github.com/xwp/wp-foo-bar/blob/d50f49fce733b66f4b2c1b03683027080e6cadbe/php/class-plugin-base.php#L273

It should be changed as follows:

```diff
- #\* @(?P<type>filter|action)\s+(?P<name>[a-z0-9\-\._]+)(?:,\s+(?P<priority>\d+))?#
+ #\* @(?P<type>filter|action)\s+(?P<name>[a-z0-9\-\._/]+)(?:,\s+(?P<priority>\d+))?#
```
