### ISSUE TITLE
Build script

### ISSUE THREAD

**Issue by yani-** [xwp/wp-foo-bar#3]
I'd like to see a build script, one that will strip all unnecessary files - tests, dotfiles etc. It should also replace version with the value of `git describe`.

**Comment by westonruter** [comment]
Woah, I didn't know about `git-describe`. Nice one. But I think actually where such a build script should be located is in the wp-dev-lib project itself: https://github.com/xwp/wp-dev-lib

And actually we do have a build script, specifically for pushing to WordPress.org plugin repo: https://github.com/xwp/wp-dev-lib/blob/master/svn-push

It grabs the version from the plugin metadata. Perhaps `git-describe` could be used to automate the updating of that metadata when initiating a build. I can see it might be useful to break up the `svn-push` script, to extract just the plain build script from the logic to do SVN pushes.

So yeah, I think we can continue this conversation on wp-dev-lib.
