### ISSUE TITLE
Xdebug 3.0.0 not compatible with PHPUnit 7

### ISSUE THREAD

**Issue by DavidCramer** [xwp/wp-foo-bar#302]
## Bug Description

Xdebug released 3.0.0, which is not compatible with PHPUnit 7, which WordPress tests requires.
The result is running with coverage throws the error `Use of undefined constant XDEBUG_CC_UNUSED - assumed 'XDEBUG_CC_UNUSED' (this will throw an Error in a future version of PHP)`

## Screenshots

<img width="760" alt="Screenshot 2020-12-02 at 10 44 31" src="https://user-images.githubusercontent.com/307466/100849584-70a6a500-348b-11eb-902a-2ddf601d811d.png">

## Changelog entry

Set PECL to install Xdebug 2.9.8

**Comment by kasparsd** [comment]
This was fixed in #325:

https://github.com/xwp/wp-foo-bar/blob/292c5c1e43a9d384f223f4315376342dc3bf20d8/bin/local-dev/wordpress/Dockerfile#L91-L93
