### ISSUE TITLE
Inability to run tests from host machine is an inconvenience

### ISSUE THREAD

**Issue by flythenimbus** [xwp/wp-foo-bar#47]
## Bug Description

I tried running `yarn test:php` from my host machine and got the following error:

```
$ yarn test:php
yarn run v1.21.1
$ composer test
> phpunit

Warning: require_once(/var/www/html/wp-includes/class-phpmailer.php): failed to open stream: No such file or directory in /Users/dugi/Code/xwp/wp-foo-bar/vendor/xwp/wordpress-tests/phpunit/includes/mock-mailer.php on line 2

Fatal error: require_once(): Failed opening required '/var/www/html/wp-includes/class-phpmailer.php' (include_path='.:/usr/local/Cellar/php/7.4.1/share/php/pear') in /Users/dugi/Code/xwp/wp-foo-bar/vendor/xwp/wordpress-tests/phpunit/includes/mock-mailer.php on line 2
PHP Warning:  require_once(/var/www/html/wp-includes/class-phpmailer.php): failed to open stream: No such file or directory in /Users/dugi/Code/xwp/wp-foo-bar/vendor/xwp/wordpress-tests/phpunit/includes/mock-mailer.php on line 2
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/wp-includes/class-phpmailer.php' (include_path='.:/usr/local/Cellar/php/7.4.1/share/php/pear') in /Users/dugi/Code/xwp/wp-foo-bar/vendor/xwp/wordpress-tests/phpunit/includes/mock-mailer.php on line 2
```

This is understandable since I don't have WP Core in my host machine. However, this present quite an inconvenience for developers to run their tests.

The way I see it, there are two options to make this friendlier:

1. Adjust scripts in `package.json` to run a `docker-compose exec ...` and execute tests scripts within the container; or
2. Remove dependency to the WordPress Tests package (not a very good idea, imo)

Please comment if you have a better alternative!

## Expected Behaviour

- Execute `yarn test:php` from your host machine
- The tests run successfully

## Steps to reproduce

- Execute `yarn test:php` from your host machine
- The command breaks with the error shown above 

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by derekherman** [comment]
Not sure why you would run test this way or with `yarn` in general. The documentation describes how to run test and that they require you to run them in the Docker container. Like so:

`npm run docker -- npm run test:php`

https://github.com/xwp/wp-foo-bar/blob/develop/contributing/engineering.md#tests
