### ISSUE TITLE
Setup i18n support

### ISSUE THREAD

**Issue by derekherman** [xwp/wp-foo-bar#74]
## Feature description

We should fully support the i18n requirements for plugins. Someone should research the latest best practices for loading translation files, describe and implement them.

**Comment by derekherman** [comment]
There two approaches here. First, add a `.pot` file and use `load_plugin_textdomain`. Second, contribute translations using translate.wordpress.org which requires WP 4.6+. I'm inclined to take the second route and close this issue. Thoughts?

**Comment by rheinardkorf** [comment]
@derekherman I'm in favour of the second approach. But it is worth noting that this applies **only** to plugins in the WordPress.org repo.  It uses the relevant project slug.

If we are writing plugins that are not distributed through the repo, then we might have to use the first approach. Yet, the first approach is not the recommended approach for repo plugins as of about 3 years ago.

**Comment by derekherman** [comment]
Closing in favor of using the .org tools.
